# Generated by Django 3.1 on 2020-08-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_position', models.CharField(max_length=100)),
                ('cam_attr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=200)),
                ('burden', models.IntegerField(default=0)),
                ('cam_choiced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.camera')),
            ],
        ),
    ]
